name: Build Obsidian Plugin

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      # 暂时跳过测试，需要进一步配置测试环境
      # - name: Run tests
      #   run: npm run automation

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-plugin-build
          path: |
            dist/main.js
            dist/manifest.json
            dist/styles.css
          retention-days: 5 