name: Publish Obsidian Plugin to Community Plugins

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (e.g., 1.5.5)'
        required: true
        default: ''
      notes:
        description: '版本更新说明'
        required: true
        default: ''

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update version in manifest.json
        uses: jossef/action-set-json-field@v2.1
        with:
          file: manifest.json
          field: version
          value: ${{ github.event.inputs.version }}

      - name: Update version in package.json
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ github.event.inputs.version }}

      - name: Update versions.json
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [ -f versions.json ]; then
            MINAPP=$(jq -r '.minAppVersion' manifest.json)
            NEWVERSIONSENTRY="\"$VERSION\": \"$MINAPP\""
            CONTENTS=$(cat versions.json | jq -r 'to_entries | map("\"\(.key)\": \"\(.value)\"") | join(",\n    ")')
            echo "{\n    $NEWVERSIONSENTRY,\n    $CONTENTS\n}" > versions.json
          fi

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.notes }}
          draft: false
          prerelease: false
          files: |
            dist/main.js
            dist/manifest.json
            dist/styles.css

      - name: Checkout community plugin repository
        uses: actions/checkout@v3
        with:
          repository: obsidian-community/obsidian-releases
          token: ${{ secrets.PLUGIN_PR_TOKEN }}
          path: obsidian-releases

      - name: Create Pull Request to Community Plugins
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PLUGIN_PR_TOKEN }}
          commit-message: "Update Diagrams plugin to v${{ github.event.inputs.version }}"
          title: "Update Diagrams plugin to v${{ github.event.inputs.version }}"
          body: |
            更新信息：
            ${{ github.event.inputs.notes }}
          branch: "update-diagrams-plugin"
          base: "master"
          path: obsidian-releases 